# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbc753749023eb9a3b88b5169e46808675423e85ec4d956287e70a618dc5faa2297a090dc8cd1c08eb33487b8c1427baa4cdb83514a9ddb1020d7b1edf380942

test:
  secret_key_base: db20bc3c450ced491655a4ce0a3287c9d7369fbe434a613b0c43d355df3cb86d047a0029fa9b0ba3a2efacb8227b743b5f9ebed2d4d9bbc4f448aa8ab59ff6f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
